version: '3'

services:
  db:
    image: postgres
    # command: --init-file /db/init.sql
    ports:
      - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
