version: '3'

services:
  db:
    # image: postgres
    build: ./db
    ports:
      - "5432:5432"
  
  imageServer:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: FM9GO6CT17O8122165HB
      MINIO_SECRET_KEY: yLyai1DFC03hzN17srK0PvYTIZFvHDnDxRKYAjK4
    command: server /data
    
  web:
    build: .
    command: python3 manage.py makemigrations
    # command: python3 manage.py migrate
    # command: uwsgi --http :8000 --module image-server-practice.wsgi  // Threading 에서 문제가 발생 -> process 갯수 조절 필요?
    # command: python3 manage.py test
    ports:
      - "8000:8000"
    depends_on:
      - db 
      - imageServer