version: '3'

services:
  db:
    build: ./db
    ports:
      - "5432:5432"
  
  imageServer:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: FM9GO6CT17O8122165HB
      MINIO_SECRET_KEY: yLyai1DFC03hzN17srK0PvYTIZFvHDnDxRKYAjK4
    command: server /data
    
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py test"
    ports:
      - "8000:8000"
    depends_on:
      - db 
      - imageServer
  front:
    build: ./frontend/
    command: [nginx, '-g', 'daemon off;']
    ports:
      - "80:80"
    depends_on:
      - web