# Generated by Django 2.1.4 on 2018-12-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(default=0),
        ),
    ]
